FROM alpine

HEALTHCHECK --interval=5m --timeout=3s \
  CMD ls -l

EXPOSE 1 2 3 4 5 6 7 8 9 10

LABEL com.swipely.iam-docker.iam-profile abcd
ENV abc asda
ENV def 1234
ENV IAM_ROLE 1235823838

VOLUME /myvolume
